version: '3'
services:
  v2ray:
    restart: always
    image: v2ray/official
    volumes:
    - ./config.json:/etc/v2ray/config.json
    - ./log/v2ray:/var/log/v2ray
  nginx:
    restart: always
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./log/nginx:/var/log/nginx
    ports:
    - 80:80
    links:
    - v2ray:v2ray